### ISSUE TITLE
PubSub lib issue?

### ISSUE THREAD

**Issue by once2go** [copercini/esp8266-aws_iot#8]
Hi. 
Cant figure out what the issue happen to me, seams tm it's something wrong with PubSub client but before wanna ask somebody if my setup is correct:
So, I already setup sketch with proper config: mqtt shadow, cert der, private key, even root CA. 
My log:

> WiFi connected
> IP address: 
> 192.168.2.73
> Heap: 45744
> Success to open cert file
> cert loaded
> Success to open private cert file
> private key loaded
> Success to open ca
> ca loaded
> Heap: 36976
> Attempting MQTT connection...pm open,type:2 0
> connected
> hello world #1
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #2
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #3
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #4
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #5
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #6
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #7
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #8
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #9
> Heap: 20680
> Attempting MQTT connection...connected
> hello world #10
> Heap: 20680

When I check my IoT monitor status, it shows me that I have "n number of successful connection" "n number of inbound messages", but when I go to **test** tool and try to subscribe to "outTopic" there is no incoming messages(device is ON and messages sends looks like successfully due to UART log). I even try to send some messages to "inTopic" from test tool but nothing happened(no incoming messages on device during ON session).  
My suggestion is that something wrong with PubSubClient from Library manager(my one https://pubsubclient.knolleary.net/ 2.6.0). 
So if anyone still use this library with config from samples, let me may be I do something wrong. 
If my suggestions is wrong, can you please advise me where I should look to fix an issue.
Thanks

**Comment by copercini** [comment]
It seems working, check if your endpoint region (for example us-west-2) is the same of the web test tool

additionally, you can try subscribe to all topics, using the wildcard #

**Comment by once2go** [comment]
Regenerate new certificate and its help_
Weird 
Any way thanks for quick response and amazing example!
